const FETCH_AUTHORS = 'authors/FETCH_AUTHORS';
const FETCH_ONE_AUTHOR = 'authors/FETCH_ONE_AUTHOR';
const START_FETCHING = 'authors/START_FETCHING';
const END_FETCHING = 'authors/END_FETCHING';
const CREATE_AUTHOR = 'authors/CREATE_AUTHOR';
const CHANGE_PAGE = 'authors/CHANGE_PAGE';
const FETCH_AUTHOR_BOOKS = 'authors/FETCH_AUTHOR_BOOKS';
const UPDATE_AUTHOR = 'authors/UPDATE_AUTHOR';

export {
    FETCH_AUTHORS,
    FETCH_ONE_AUTHOR,
    CREATE_AUTHOR,
    FETCH_AUTHOR_BOOKS,
    CHANGE_PAGE,
    UPDATE_AUTHOR,
    START_FETCHING,
    END_FETCHING
}